//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public int ProductYearAging { get; set; }
        public float ProductPrice { get; set; }
        public int ProductCapacity { get; set; }
        public string ProductOrigin { get; set; }
        public int ProductCategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
